rule collect_and_delete:
    input:
        [f"{i}.txt" for i in range(100)],
    run:
        shell("rm {input}")


rule create:
    output:
        "{i}.txt",
    run:
        shell("touch {output}")
