jobscript: "grid-jobscript.sh"
cluster: "grid-submit.py"
cluster-status: "grid-status.py"
max-jobs-per-second: 100
max-status-checks-per-second: 100
restart-times: 5
local-cores: 10
jobs: 5000
verbose: false
